SELECT 
--COLUMNS
    X.U_BookingNumber, 
    X.U_BookingNumber AS U_BookingId,
    X.bi_DisableTableRow AS DisableTableRow, 
    X.bi_DisableSomeFields AS DisableSomeFields, 
    X.bi_Code AS Code, 
    X.U_BookingDate, 
    X.bi_U_PODNum AS U_PODNum, 
    X.U_PODSONum, 
    X.U_CustomerName, 
    X.U_SAPClient, 
    X.U_PlateNumber, 
    X.U_VehicleTypeCap, 
    X.U_DeliveryStatus, 
    X.U_DeliveryDatePOD,
    X.U_NoOfDrops, 
    X.U_TripType, 
    X.U_ClientReceivedDate, 
    X.U_ActualHCRecDate, 
    X.U_PODinCharge, 
    X.U_VerifiedDateHC, 
    X.U_PTFNo, 
    X.U_DateForwardedBT, 
    X.U_BillingDeadline, 
    X.U_BillingStatus, 
    X.bi_U_BillingTeam AS U_BillingTeam, 
    X.U_GrossInitialRate, 
    X.U_Demurrage,
    X.U_AddCharges, 
    X.U_ActualBilledRate, 
    X.bi_U_RateAdjustments AS U_RateAdjustments, 
    X.bi_U_ActualDemurrage AS U_ActualDemurrage, 
    X.U_ActualAddCharges, 
    X.U_TotalRecClients, 
    X.U_CheckingTotalBilled, 
    X.U_Checking, 
    X.U_CWT2307, 
    X.U_SOBNumber, 
    X.U_ForwardLoad, 
    X.po_U_BackLoad AS U_BackLoad,
    X.U_TypeOfAccessorial, 
    X.U_TimeInEmptyDem, 
    X.U_TimeOutEmptyDem, 
    X.U_VerifiedEmptyDem, 
    X.U_TimeInLoadedDem, 
    X.U_TimeOutLoadedDem, 
    X.U_VerifiedLoadedDem, 
    X.U_TimeInAdvLoading, 
    X.U_DayOfTheWeek, 
    X.U_TimeIn, 
    X.U_TimeOut,
    X.U_TotalExceed, 
    X.U_ODOIn, 
    X.U_ODOOut, 
    X.U_TotalUsage, 
    X.U_SOLineNum, 
    X.U_ARInvLineNum, 
    X.U_TotalAR, 
    X.U_VarAR, 
    X.U_ServiceType, 
    X.U_DocNum, 
    X.U_InvoiceNo, 
    X.U_DeliveryReceiptNo, 
    X.U_SeriesNo, 
    X.U_GroupProject, 
    X.U_DeliveryOrigin,
    X.U_Destination, 
    X.U_OtherPODDoc, 
    X.U_RemarksPOD, 
    X.U_PODStatusDetail, 
    X.U_BTRemarks, 
    X.U_DestinationClient, 
    X.U_Remarks, 
    X.U_Attachment, 
    X.U_SI_DRNo, 
    X.U_TripTicketNo, 
    X.U_WaybillNo, 
    X.U_ShipmentManifestNo, 
    X.U_OutletNo, 
    X.U_CBM,
    X.U_DeliveryMode, 
    X.U_SourceWhse, 
    X.U_SONo, 
    X.U_NameCustomer, 
    X.U_CategoryDR, 
    X.U_IDNumber, 
    X.U_Status, 
    X.U_TotalInvAmount
--COLUMNS
FROM PCTP_UNIFIED X WITH (NOLOCK) 