ALTER TABLE PCTP_WINDOW_JSON_LOG 
DROP CONSTRAINT event_type_chk;

ALTER TABLE PCTP_WINDOW_JSON_LOG
ADD CONSTRAINT event_type_chk 
CHECK (event_type in ('UPDATE', 'CREATE_SO', 'CREATE_AR', 'CREATE_AP'))
;