-------->>CREATING TARGETS

DROP TABLE IF EXISTS TMP_TARGET_20230907
SELECT
    POD.U_BookingNumber,
    ISNULL(PRICING.U_BoomTruck2, 0) AS U_BoomTruckTP,
    ISNULL(PRICING.U_BoomTruck, 0) AS U_BoomTruckPRICING,
    ISNULL(TP.U_BoomTruck2, 0) AS U_BoomTruck2TP,
    ISNULL(PRICING.U_BoomTruck2, 0) AS U_BoomTruck2PRICING
INTO TMP_TARGET_20230907
FROM [dbo].[@PCTP_POD] POD WITH (NOLOCK)
    LEFT JOIN [dbo].[@PCTP_TP] TP ON POD.U_BookingNumber = TP.U_BookingId
    LEFT JOIN [dbo].[@PCTP_PRICING] PRICING ON POD.U_BookingNumber = PRICING.U_BookingId;

-------->>TP_EXTRACT

SELECT U_BookingId AS U_BookingNumber, U_BoomTruck, U_BoomTruck2
INTO TP_EXTRACT_36_BAK_20230907PM
FROM TP_EXTRACT;

UPDATE TP_EXTRACT
SET U_BoomTruck = TMP.U_BoomTruckTP,
    U_BoomTruck2 = TMP.U_BoomTruck2TP
FROM TMP_TARGET_20230907 TMP
WHERE TMP.U_BookingNumber = TP_EXTRACT.U_BookingNumber;

-------->>PRICING_EXTRACT

SELECT U_BookingId AS U_BookingNumber, U_BoomTruck, U_BoomTruck2
INTO PRICING_EXTRACT_36_BAK_20230907PM
FROM PRICING_EXTRACT;

UPDATE PRICING_EXTRACT
SET U_BoomTruck = TMP.U_BoomTruckPRICING,
    U_BoomTruck2 = TMP.U_BoomTruck2PRICING
FROM TMP_TARGET_20230907 TMP
WHERE TMP.U_BookingNumber = PRICING_EXTRACT.U_BookingNumber;

-------->>DELETING TMP_TARGET_20230907

DROP TABLE IF EXISTS TMP_TARGET_20230907