-------->>CREATING TARGETS
    
    DROP TABLE IF EXISTS TMP_TARGET_20230914
    SELECT
    POD.U_BookingNumber,
    CAST(POD.U_OtherPODDoc as nvarchar(1000)) AS U_OtherPODDoc
    INTO TMP_TARGET_20230914
    FROM [dbo].[@PCTP_POD] POD  WITH (NOLOCK)

-------->>POD_EXTRACT

    UPDATE POD_EXTRACT
    SET U_OtherPODDoc = TMP.U_OtherPODDoc
    FROM TMP_TARGET_20230914 TMP
    WHERE TMP.U_BookingNumber = POD_EXTRACT.U_BookingNumber

-------->>BILLING_EXTRACT

    UPDATE BILLING_EXTRACT
    SET U_OtherPODDoc = TMP.U_OtherPODDoc
    FROM TMP_TARGET_20230914 TMP
    WHERE TMP.U_BookingNumber = BILLING_EXTRACT.U_BookingId

-------->>TP_EXTRACT

    UPDATE TP_EXTRACT
    SET U_OtherPODDoc = TMP.U_OtherPODDoc
    FROM TMP_TARGET_20230914 TMP
    WHERE TMP.U_BookingNumber = TP_EXTRACT.U_BookingId

-------->>DELETING TMP_TARGET_20230914

    DROP TABLE IF EXISTS TMP_TARGET_20230914