SELECT
U_BookingNumber,
U_DeliveryStatus,
U_PODStatusDetail
INTO PCTP_POD_DELIVERY_STATUS_POD_STATUS_20230724BAK
FROM [@PCTP_POD]
WHERE U_DeliveryStatus NOT IN ('Delivered', 'Irregular')
    AND U_PODStatusDetail IS NOT NULL AND CAST(U_PODStatusDetail AS nvarchar(max)) <> ''

UPDATE [@PCTP_POD]
SET U_PODStatusDetail = NULL
FROM PCTP_POD_DELIVERY_STATUS_POD_STATUS_20230724BAK BAK
WHERE BAK.U_BookingNumber = [@PCTP_POD].U_BookingNumber

UPDATE SUMMARY_EXTRACT
SET U_PODStatusDetail = NULL
FROM PCTP_POD_DELIVERY_STATUS_POD_STATUS_20230724BAK BAK
WHERE BAK.U_BookingNumber = SUMMARY_EXTRACT.U_BookingNumber

UPDATE POD_EXTRACT
SET U_PODStatusDetail = NULL
FROM PCTP_POD_DELIVERY_STATUS_POD_STATUS_20230724BAK BAK
WHERE BAK.U_BookingNumber = POD_EXTRACT.U_BookingNumber

UPDATE BILLING_EXTRACT
SET U_PODStatusDetail = NULL
FROM PCTP_POD_DELIVERY_STATUS_POD_STATUS_20230724BAK BAK
WHERE BAK.U_BookingNumber = BILLING_EXTRACT.U_BookingNumber